import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import "./globals.css";
import LoginModal from "@/components/modals/LoginModal";
import { getCurrentUser } from "@/services/getCurrentUser";
import NavBar from "@/components/Navbar";
import Heading from "@/components/Heading";
import ClientOnly from "@/components/ClientOnly";
import Provider from "@/components/Provider";
import { getCurrentUserInfo } from "@/services/getCurrentUserInfo";


export const metadata = {
  title: "بارانداز - تجارت خانه ای به وسعت ایران",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser=await getCurrentUser()
  const userInfo=await getCurrentUserInfo()
 

  return (
    <html lang="fa" dir="rtl" charSet="utf-8">
      <body>
        <Provider>
        <NavBar userInfo={userInfo} currentUser={currentUser}/>
        <LoginModal/>
        {children}
        </Provider>
      </body>
    </html>
  );
}
